version: "3"
services:
  chatgpt-discord-bot:
    container_name: chatgpt-discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    # ports:
    #     - "8081:8080"
